# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Tareas\Practica2\interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(739, 479)
        self.mover = QtWidgets.QPushButton(Dialog)
        self.mover.setGeometry(QtCore.QRect(530, 370, 75, 23))
        self.mover.setObjectName("mover")
        self.combo = QtWidgets.QComboBox(Dialog)
        self.combo.setGeometry(QtCore.QRect(80, 360, 101, 22))
        self.combo.setObjectName("combo")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo2 = QtWidgets.QComboBox(Dialog)
        self.combo2.setGeometry(QtCore.QRect(240, 360, 91, 22))
        self.combo2.setObjectName("combo2")
        self.combo2.addItem("")
        self.combo2.addItem("")
        self.combo2.addItem("")
        self.Poste2 = QtWidgets.QLabel(Dialog)
        self.Poste2.setGeometry(QtCore.QRect(360, 90, 46, 180))
        self.Poste2.setAutoFillBackground(False)
        self.Poste2.setStyleSheet("background-color: blue")
        self.Poste2.setText("")
        self.Poste2.setObjectName("Poste2")
        self.Poste1 = QtWidgets.QLabel(Dialog)
        self.Poste1.setGeometry(QtCore.QRect(110, 90, 46, 180))
        self.Poste1.setAutoFillBackground(False)
        self.Poste1.setStyleSheet("background-color: blue")
        self.Poste1.setText("")
        self.Poste1.setObjectName("Poste1")
        self.Poste3 = QtWidgets.QLabel(Dialog)
        self.Poste3.setGeometry(QtCore.QRect(610, 90, 46, 180))
        self.Poste3.setAutoFillBackground(False)
        self.Poste3.setStyleSheet("background-color: blue")
        self.Poste3.setText("")
        self.Poste3.setObjectName("Poste3")
        self.Disco1 = QtWidgets.QLabel(Dialog)
        self.Disco1.setGeometry(QtCore.QRect(100, 110, 60, 20))
        self.Disco1.setAutoFillBackground(False)
        self.Disco1.setStyleSheet("background-color: orange\n"
"")
        self.Disco1.setText("")
        self.Disco1.setObjectName("Disco1")
        self.Disco2 = QtWidgets.QLabel(Dialog)
        self.Disco2.setGeometry(QtCore.QRect(90, 130, 80, 20))
        self.Disco2.setAutoFillBackground(False)
        self.Disco2.setStyleSheet("background-color: orange\n"
"")
        self.Disco2.setText("")
        self.Disco2.setObjectName("Disco2")
        self.Disco3 = QtWidgets.QLabel(Dialog)
        self.Disco3.setGeometry(QtCore.QRect(80, 150, 100, 20))
        self.Disco3.setAutoFillBackground(False)
        self.Disco3.setStyleSheet("background-color: orange\n"
"")
        self.Disco3.setText("")
        self.Disco3.setObjectName("Disco3")
        self.Disco4 = QtWidgets.QLabel(Dialog)
        self.Disco4.setGeometry(QtCore.QRect(70, 170, 120, 20))
        self.Disco4.setAutoFillBackground(False)
        self.Disco4.setStyleSheet("background-color: orange\n"
"")
        self.Disco4.setText("")
        self.Disco4.setObjectName("Disco4")
        self.Disco5 = QtWidgets.QLabel(Dialog)
        self.Disco5.setGeometry(QtCore.QRect(60, 190, 140, 20))
        self.Disco5.setAutoFillBackground(False)
        self.Disco5.setStyleSheet("background-color: orange\n"
"")
        self.Disco5.setText("")
        self.Disco5.setObjectName("Disco5")
        self.Disco6 = QtWidgets.QLabel(Dialog)
        self.Disco6.setGeometry(QtCore.QRect(50, 210, 160, 20))
        self.Disco6.setAutoFillBackground(False)
        self.Disco6.setStyleSheet("background-color: orange\n"
"")
        self.Disco6.setText("")
        self.Disco6.setObjectName("Disco6")
        self.Disco7 = QtWidgets.QLabel(Dialog)
        self.Disco7.setGeometry(QtCore.QRect(40, 230, 180, 20))
        self.Disco7.setAutoFillBackground(False)
        self.Disco7.setStyleSheet("background-color: orange\n"
"")
        self.Disco7.setText("")
        self.Disco7.setObjectName("Disco7")
        self.Disco8 = QtWidgets.QLabel(Dialog)
        self.Disco8.setGeometry(QtCore.QRect(30, 250, 200, 20))
        self.Disco8.setAutoFillBackground(False)
        self.Disco8.setStyleSheet("background-color: orange\n"
"")
        self.Disco8.setText("")
        self.Disco8.setObjectName("Disco8")
        self.label1 = QtWidgets.QLabel(Dialog)
        self.label1.setGeometry(QtCore.QRect(110, 290, 47, 13))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(360, 290, 47, 13))
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(Dialog)
        self.label3.setGeometry(QtCore.QRect(610, 290, 47, 13))
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(Dialog)
        self.label4.setGeometry(QtCore.QRect(80, 340, 101, 16))
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(Dialog)
        self.label5.setGeometry(QtCore.QRect(240, 340, 101, 16))
        self.label5.setObjectName("label5")
        self.label6 = QtWidgets.QLabel(Dialog)
        self.label6.setGeometry(QtCore.QRect(10, 450, 101, 16))
        self.label6.setObjectName("label6")
        self.label7 = QtWidgets.QLabel(Dialog)
        self.label7.setGeometry(QtCore.QRect(150, 450, 151, 16))
        self.label7.setObjectName("label7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Torre de Hanói"))
        self.mover.setText(_translate("Dialog", "mover"))
        self.combo.setItemText(0, _translate("Dialog", "Poste 1"))
        self.combo.setItemText(1, _translate("Dialog", "Poste 2"))
        self.combo.setItemText(2, _translate("Dialog", "Poste 3"))
        self.combo2.setItemText(0, _translate("Dialog", "Poste 1"))
        self.combo2.setItemText(1, _translate("Dialog", "Poste 2"))
        self.combo2.setItemText(2, _translate("Dialog", "Poste 3"))
        self.label1.setText(_translate("Dialog", "Poste 1"))
        self.label2.setText(_translate("Dialog", "Poste 2"))
        self.label3.setText(_translate("Dialog", "Poste 3"))
        self.label4.setText(_translate("Dialog", "Seleccionar disco en:"))
        self.label5.setText(_translate("Dialog", "Mover a:"))
        self.label6.setText(_translate("Dialog", "Jugadas realizadas: "))
        self.label7.setText(_translate("Dialog", "Número de movimientos: 0"))
